### ISSUE TITLE
To a function called independently, return Ip / Port?

### ISSUE THREAD

**Issue by w2n1ck** [djhohnstein/portscanner#1]
To a function called independently, return Ip / Port?

**Comment by djhohnstein** [comment]
I'm afraid I don't understand the question.

**Comment by w2n1ck** [comment]
like python:

def scan(*key,**args):
    /*scan*/
    return host,open_port_list

So，I can use it like this：

from ctypes import *
lib = cdll.LoadLibrary(u'./scan.so')
results =lib.Scan("14.215.177.38","1-1024","eth0") # ip,端口范围，网卡
...
nmap(results....)

**Comment by w2n1ck** [comment]
I've made it
